# Archivo de credenciales - NO COMMITAR ESTE ARCHIVO
# Agregar a .gitignore

[api]
# API Keys
main_key = "ckhhaTk5RXNselhQTTU4UTludUs3WjdJaCtGWlpJWkhVbndMY3did0dQWT0K"

[database]
# Credenciales de BD (si se usan)
# username = ""
# password = ""

[external_services]
# Claves para servicios externos
# openweather_api_key = ""
# google_maps_api_key = ""
